### ISSUE TITLE
TypeError: this.mesh.geometry.area is not a function

### ISSUE THREAD

**Issue by garciaba** [leapmotion/leapjs-widgets#4]
Im getting this error in this line in InteractablePlane, in this line:

  this.mass = this.mesh.geometry.area() \* this.density;

Any clue?

**Comment by pehrlich** [comment]
`#area` is a custom method added by this project to particular THREE.js geometries.  

This error occurs when you try and turn a non-supported geometry in to a button.  Supported geometries are `PlaneGeometry` and `CircleGeometry`.

I have some code sitting around from MozVR which will scale a box to make it look like it is being pushed by a plane.  Here: https://github.com/leapmotion/HIRO/blob/master/js/vrhud.js#L290-L319  Note that scale must be used, because that's the only way to resize an initialized THREE.js geometry.
